apiVersion: v1
kind: Pod
metadata:
  name: my-annotation-pod
  annotations:
    owner: xyz@ipspecialist.com
    git-commit: bd7833kjgll20xj3
spec:
  containers:
  - name: nginx
    image: nginx